server {
    listen 80;
    server_name lingoaz.online www.lingoaz.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name lingoaz.online www.lingoaz.online;

    ssl_certificate /etc/letsencrypt/live/lingoaz.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lingoaz.online/privkey.pem;

    index index.php index.html;

    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}